vim.pack.add({
	"https://github.com/nickshiro/arc.nvim",
	"https://github.com/catppuccin/nvim",
}, { confirm = false })

vim.cmd.colorscheme("arc")

-- return {
-- 	{
-- 		dir = "~/w/arc.nvim",
-- 		config = function()
-- 			vim.cmd("colorscheme arc")
-- 		end,
-- 	},
-- 	-- {
-- 	--     "nickshiro/arc.nvim",
-- 	--     name = "arc",
-- 	--     config = function()
-- 	--         vim.cmd("colorscheme arc")
-- 	--     end
-- 	-- },
-- 	{
-- 		"catppuccin/nvim",
-- 		name = "catppuccin",
-- 		config = function() end,
-- 	},
-- 	{
-- 		"bjarneo/pixel.nvim",
-- 		name = "pixel",
-- 		priority = 1000,
-- 		config = function() end,
-- 	},
-- 	{
-- 		"sharpchen/Eva-Theme.nvim",
-- 		name = "eva",
-- 		lazy = true,
-- 		config = function() end,
-- 	},
-- 	{
-- 		"rebelot/kanagawa.nvim",
-- 		name = "kanagawa",
-- 		lazy = true,
-- 		config = function()
-- 			require("kanagawa")
-- 		end,
-- 	},
-- 	{
-- 		"rose-pine/neovim",
-- 		name = "rose-pine",
-- 		lazy = true,
-- 		config = function()
-- 			require("rose-pine").setup({})
-- 		end,
-- 	},
-- 	{
-- 		"Everblush/nvim",
-- 		name = "everblush",
-- 		lazy = true,
-- 		config = function()
-- 			require("everblush").setup({})
-- 		end,
-- 	},
-- 	{
-- 		"sam4llis/nvim-tundra",
-- 		name = "tundra",
-- 		lazy = true,
-- 	},
-- 	{
-- 		"folke/tokyonight.nvim",
-- 		name = "tokyonight",
-- 		lazy = true,
-- 		config = function()
-- 			require("tokyonight").setup({})
-- 		end,
-- 	},
-- 	{
-- 		"vague2k/vague.nvim",
-- 		name = "vague",
-- 		lazy = true,
-- 		config = function()
-- 			require("vague").setup({})
-- 		end,
-- 	},
-- 	{
-- 		"olivercederborg/poimandres.nvim",
-- 		name = "poimandres",
-- 		lazy = true,
-- 		config = function()
-- 			require("poimandres").setup({})
-- 		end,
-- 	},
-- }
