require("plugins.local.statusline")
require("plugins.local.formatter")

require("plugins.cmp")
require("plugins.colorizer")
require("plugins.devicons")
require("plugins.lsp")
require("plugins.ibl")
require("plugins.neocord")
require("plugins.sessions")
require("plugins.telescope")
require("plugins.themes")
require("plugins.tree")
require("plugins.treesitter")
require("plugins.treesitter-context")

vim.pack.add({ "https://github.com/nvim-mini/mini.trailspace" }, { confirm = false })
