require("plugins.local.statusline").setup()

require("plugins.cmp")
require("plugins.colorizer")
require("plugins.devicons")
require("plugins.formatter")
require("plugins.lsp")
require("plugins.ibl")
require("plugins.neocord")
require("plugins.sessions")
require("plugins.telescope")
require("plugins.themes")
require("plugins.trailspace")
require("plugins.tree")
require("plugins.treesitter")
require("plugins.treesitter-context")
